# Generated by Django 6.0.2 on 2026-03-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usename',
            field=models.CharField(default='demouser', max_length=50),
            preserve_default=False,
        ),
    ]
