# Generated by Django 6.0.2 on 2026-03-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_usename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usename',
        ),
    ]
