# Generated by Django 6.0.3 on 2026-03-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookcopy_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
