# Generated by Django 6.0.3 on 2026-03-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_returned', models.BooleanField(default=False)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='books.bookcopy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borrows',
                'indexes': [models.Index(fields=['user'], name='borrows_user_id_9a0e59_idx'), models.Index(fields=['due_date'], name='borrows_due_dat_86b24c_idx'), models.Index(fields=['is_returned'], name='borrows_is_retu_49a72c_idx')],
            },
        ),
    ]
