# Generated by Django 6.0.2 on 2026-03-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['user'], name='borrows_user_id_9a0e59_idx'),
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['due_date'], name='borrows_due_dat_86b24c_idx'),
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['is_returned'], name='borrows_is_retu_49a72c_idx'),
        ),
    ]
